[versions]
androidPluginGradle = "8.7.2"
androidx-activity = "1.9.3"
androidx-compose-mobile = "1.7.5"
androidx-compose-wear = "1.4.0"
androidx-lifecycle = "2.8.7"
androidx-wear = "1.3.0"
desugarJdkLib = "2.1.3"
dagger = "2.52"
horologist-layout = "0.4.8"
libsu = "5.2.1"
logcat = "0.1"
kotlin = "2.0.21"
kotlin-coroutines = "1.9.0"
kotlinova = "3.2.0"
playServices-wearable = "19.0.0"
versionsPlugin = "0.51.0"
wire = "4.9.9"

[libraries]
androidPluginGradle = { module = "com.android.tools.build:gradle", version.ref = "androidPluginGradle" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-mobile" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-mobile" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose-mobile" }
androidx-compose-wear-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-compose-wear" }
androidx-compose-wear-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-compose-wear" }
androidx-compose-wear-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx-compose-wear" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "androidx-wear" }
dagger-hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
dagger-hilt-runtime = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
desugarJdkLib = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLib" }
horologist-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologist-layout" }
libsu = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
libsu-io = { module = "com.github.topjohnwu.libsu:io", version.ref = "libsu" }
logcat = { module = "com.squareup.logcat:logcat", version.ref = "logcat" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-plugin-compose = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
kotlin-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlin-coroutines" }
kotlinova-core = { module = "si.inova.kotlinova:core", version.ref = "kotlinova" }
kotlinova-gradle = { module = "si.inova.kotlinova:gradle", version.ref = "kotlinova" }
playServices-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "playServices-wearable" }
versionsPlugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsPlugin" }
wire-runtime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }
wire-pluginGradle = { module = "com.squareup.wire:wire-gradle-plugin", version.ref = "wire" }
