[versions]
androidPluginGradle = "8.0.1"
androidx-activity = "1.7.1"
androidx-compose-compiler = "1.4.7"
androidx-compose-mobile = "1.4.3"
androidx-compose-wear = "1.1.2"
androidx-lifecycle = "2.6.1"
androidx-wear = "1.2.0"
dagger = "2.46.1"
horologist-layout = "0.4.8"
libsu = "5.0.5"
logcat = "0.1"
kotlin = "1.8.21"
kotlin-coroutines = "1.7.1"
kotlinova = "3.0.0-alpha11"
playServices-wearable = "18.0.0"
versionsPlugin = "0.46.0"
wire = "4.6.2"

[libraries]
androidPluginGradle = { module = "com.android.tools.build:gradle", version.ref = "androidPluginGradle" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose-compiler" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-mobile" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-mobile" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose-mobile" }
androidx-compose-wear-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-compose-wear" }
androidx-compose-wear-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-compose-wear" }
androidx-compose-wear-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx-compose-wear" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "androidx-wear" }
dagger-hilt-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
dagger-hilt-runtime = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
horologist-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologist-layout" }
libsu = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
libsu-io = { module = "com.github.topjohnwu.libsu:io", version.ref = "libsu" }
logcat = { module = "com.squareup.logcat:logcat", version.ref = "logcat" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlin-coroutines" }
kotlinova-gradle = { module = "si.inova.kotlinova:gradle", version.ref = "kotlinova" }
playServices-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "playServices-wearable" }
versionsPlugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versionsPlugin" }
wire-runtime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }
wire-pluginGradle = { module = "com.squareup.wire:wire-gradle-plugin", version.ref = "wire" }
