[versions]
androidPluginGradle = "7.0.3"
androidx-activity = "1.4.0"
androidx-compose = "1.1.0-beta02"
androidx-compose-wear = "1.0.0-alpha10"
androidx-wear = "1.2.0"
logcat = "0.1"
kotlin = "1.5.31"
playServices-wearable = "17.1.0"
wire = "3.7.0"

[libraries]
androidPluginGradle = { module = "com.android.tools.build:gradle", version.ref = "androidPluginGradle" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx.activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx.activity" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx.compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx.compose" }
androidx-compose-wear-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx.compose.wear" }
androidx-compose-wear-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx.compose.wear" }
androidx-compose-wear-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx.compose.wear" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "androidx.wear" }
logcat = { module = "com.squareup.logcat:logcat", version.ref = "logcat" }
kotlin-pluginGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
playServices-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "playServices.wearable" }
wire-runtime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }
wire-pluginGradle = { module = "com.squareup.wire:wire-gradle-plugin", version.ref = "wire" }
